UniversityApp/UniversityApp/Controllers/CoursesController.cs
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using UniversityApp.Core;
using UniversityApp.Core.DomainEntities;
using UniversityApp.Core.DTOs;
using UniversityApp.Core.Interfaces.Services;
using UniversityApp.Presentation.Controllers;

namespace UniversityApp.Controllers
{
    public class CoursesController : Controller
    {
        private readonly ICourseService courseService;
        private readonly IMapper mapper;

        public CoursesController(ICourseService courseService, IMapper mapper)
        {
            this.courseService = courseService;
            this.mapper = mapper;
        }

        [Authorize(Roles = Constants.SecretaryRole)]
        public async Task<IActionResult> Index()
        {
            return View(mapper.Map<IEnumerable<CourseDto>>(await courseService.GetAllAsync()));
        }

        [Authorize(Roles = Constants.SecretaryRole)]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(
            [Bind("CourseTitle,NoCredits,Year,Semester")] CourseDto course)
        {
            if (ModelState.IsValid)
            {
                await courseService.AddAsync(mapper.Map<Course>(course));
                return RedirectToAction(nameof(Index));
            }
            return View(course);
        }

        [Authorize(Roles = Constants.SecretaryRole)]
        public async Task<IActionResult> Edit(Guid? id)
        {
            return await GetCourseView(id);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Guid id, [Bind("Id,CourseTitle,NoCredits,Year,Semester")] CourseDto course)
        {
            if (ModelState.IsValid)
            {
                await courseService.UpdateAsync(mapper.Map<Course>(course));

                return RedirectToAction(nameof(Index));
            }
            return View(course);
        }

        [Authorize(Roles = Constants.SecretaryRole)]
        public async Task<IActionResult> Delete(Guid? id)
        {
            return await GetCourseView(id);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(Guid id)
        {
            await courseService.DeleteAsync(id);
            return RedirectToAction(nameof(Index));
        }

        private async Task<IActionResult> GetCourseView(Guid? id)
        {
            if (id == null)
            {
                return RedirectToAction(nameof(ErrorsController.EntityNotFound), "Errors");
            }

            var course = await courseService.GetFirstOrDefaultAsync(c => c.Id == id);
            if (course == null)
            {
                return RedirectToAction(nameof(ErrorsController.EntityNotFound), "Errors");
            }
            return View(mapper.Map<CourseDto>(course));
        }
    }
}

UniversityApp/UniversityApp/Controllers/TeachedCoursesController.cs
using System;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using UniversityApp.Core.DomainEntities;
using UniversityApp.Core.Interfaces.Services;
using UniversityApp.Core.ViewModels;
using UniversityApp.Presentation.Controllers;

namespace UniversityApp.Controllers
{
    public class TeachedCoursesController : Controller
    {
        private readonly ITeachedCourseService teachedCourseService;
        private readonly ICourseService courseService;
        private readonly ITeacherService teacherService;

        public TeachedCoursesController(
            ITeachedCourseService teachedCourseService,
            ICourseService courseService,
            ITeacherService teacherService)
        {
            this.teachedCourseService = teachedCourseService;
            this.courseService = courseService;
            this.teacherService = teacherService;
        }

        [Authorize]
        public async Task<IActionResult> Create()
        {
            var teachers = (await teacherService.GetAsync()).ToList();
            teachers.ForEach(t => t.FullName = $"{t.LastName} {t.FirstName}");

            ViewData["CourseTitle"] = new SelectList(
                (await courseService.GetAllAsync()).OrderBy(x => x.CourseTitle), "CourseTitle", "CourseTitle");
            ViewData["TeacherCnp"] = new SelectList(teachers.OrderBy(x => x.FullName), "Cnp", "FullName");
            return View();
        }
        
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(CourseAssignmentViewModel model)
        {
            if (ModelState.IsValid)
            {
                await teachedCourseService.AssignCourseAsync(model);
                return RedirectToAction("Home", "Secretaries");
            }
            ViewData["CourseTitle"] = new SelectList(
                (await courseService.GetAllAsync()).OrderBy(x => x.CourseTitle),
                "CourseTitle",
                "CourseTitle");
            ViewData["TeacherCnp"] = new SelectList(
                (await teacherService.GetAsync()).OrderBy(x => x.FullName),
                "Cnp",
                "Cnp");
            return View(model);
        }

        [Authorize]
        public async Task<IActionResult> Edit(Guid? id)
        {
            if (id == null)
            {
                return RedirectToAction(nameof(ErrorsController.EntityNotFound), "Errors");
            }

            var teachedCourses = await teachedCourseService.GetFirstOrDefaultAsync(tc => tc.Id == id);
            if (teachedCourses == null)
            {
                return RedirectToAction(nameof(ErrorsController.EntityNotFound), "Errors");
            }

            ViewData["CourseId"] = new SelectList(await courseService.GetAllAsync(), "CourseId", "CourseId", teachedCourses.CourseId);
            ViewData["TeacherId"] = new SelectList(await teacherService.GetAsync(), "TeacherId", "TeacherId", teachedCourses.TeacherId);
            return View(teachedCourses);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Guid id, [Bind("Id,TeacherId,CourseId")] TeachedCourse teachedCourses)
        {
            if (id != teachedCourses.Id)
            {
                return RedirectToAction(nameof(ErrorsController.EntityNotFound), "Errors");
            }

            if (ModelState.IsValid)
            {
                await teachedCourseService.UpdateAsync(teachedCourses);
                return RedirectToAction("Home", "Secretaries");
            }
            ViewData["CourseId"] = new SelectList(await courseService.GetAllAsync(), "CourseId", "CourseId", teachedCourses.CourseId);
            ViewData["TeacherId"] = new SelectList(await teacherService.GetAsync(), "TeacherId", "TeacherId", teachedCourses.TeacherId);
            return View(teachedCourses);
        }

        // this function will print a message if the course is already assigned to the same teacher i want to assign the course 
        public async Task<IActionResult> GetInfo(string courseTitle, string teacherCnp)
        {
            var teacher = await teacherService.GetFirstOrDefaultAsync(t => String.Equals(t.Cnp, teacherCnp));
            var course = await courseService.GetFirstOrDefaultAsync(c => String.Equals(c.CourseTitle, courseTitle));
            string info = " ";
            if(teacher != null && course != null)
            {
                var teachedCourse = await teachedCourseService.GetFirstOrDefaultAsync(
                    tc => (tc.CourseId == course.Id) && (tc.TeacherId == teacher.Id));
                if(teachedCourse != null)
                {
                    info += "this item already exists!";
                }
            }
            return Json(info);
        }

        public async Task<IActionResult> GetTeachersByCourseId(string courseId)
        {
            var teachers = await teachedCourseService.GetTeachersByCourseIdAsync(new Guid(courseId));
            var result = teachers.Select(x => new
            {
                Id = x.Id,
                FullName = $"{x.LastName} {x.FirstName}"
            });
            return Json(result);
        }
    }
}

UniversityApp/UniversityApp/Views/Shared/_AllCoursesPartial.cshtml
@model IEnumerable<CourseDto>

<table class="table table-dark" aria-labelledby="UniversityApp">
    <thead>
        <tr>
            <th scope="col">
                @Html.DisplayNameFor(model => model.CourseTitle)
            </th>
            <th scope="col">
                @Html.DisplayNameFor(model => model.NoCredits)
            </th>
            <th scope="col">
                @Html.DisplayNameFor(model => model.Year)
            </th>
            <th scope="col">
                @Html.DisplayNameFor(model => model.Semester)
            </th>
            <th scope="col"></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.CourseTitle)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.NoCredits)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Year)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Semester)
            </td>
            @if (User.IsInRole("Secretary"))
            {
                <td>
                    <a asp-controller="Courses" asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                    <a asp-controller="Courses" asp-action="Delete" asp-route-id="@item.Id">Delete</a>
                </td>
            }
            else if (User.IsInRole("Teacher"))
            {
                <td>
                    <a asp-controller="Students" asp-action="EnrolledStudents" asp-route-courseId="@item.Id">Students</a>
                </td>
            }
        </tr>
        }
    </tbody>
</table>

UniversityApp/UniversityApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - UniversityApp</title>

    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/home.css" type="text/css" />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    <!-- jQuery library -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <!-- Latest compiled JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>

</head>
<body id="page-body">
    <header>
        <nav class="topnav">
            <partial name="_LoginPartial" />
        </nav>
    </header>



    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer fixed-bottom text-dark">
        <div class="container">
            &copy; 2020 - UniversityApp
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

UniversityApp/UniversityApp/Views/Shared/_LoggedInPopupPartial.cshtml
<div class="modal" tabindex="-1" role="dialog" id="loggedInPopup">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title"> </h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <p>You have successfully logged in!</p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>

<script type="text/javascript">
    $(document).ready(function () {
        if (sessionStorage.getItem('wasLoggedInPopupDisplayed') !== '1') {
            $('#loggedInPopup').modal('show');
            sessionStorage.setItem('wasLoggedInPopupDisplayed', '1');
        }
    });
</script>

UniversityApp/UniversityApp/Views/Shared/_SecretariesLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - UniversityApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" type="text/css" />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.4/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.0.1/js/bootstrap.min.js"></script>
    <link href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.0.1/css/bootstrap.min.css" rel="stylesheet" />
    <script src="~/js/site.js" type="application/javascript"></script>
</head>
<body class="secretaryBackground" onload="GetUserPicture()">
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark border-bottom box-shadow mb-3">
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                <ul class="navbar-nav flex-grow-1">
                    <li class="nav-item"><a class="nav-link text-light" asp-area="" asp-controller="Secretaries" asp-action="Home">Home</a></li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            Enrollments
                        </a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                            <a class="dropdown-item" asp-area="" asp-controller="Enrollments" asp-action="Create">Enroll student</a>
                            <a class="dropdown-item" asp-area="" asp-controller="Enrollments" asp-action="Delete">Delete</a>
                            <a class="dropdown-item" asp-area="" asp-controller="Enrollments" asp-action="Index">View enrollments</a>
                        </div>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            Courses
                        </a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                            <a class="dropdown-item" asp-area="" asp-controller="Courses" asp-action="Create">Add course</a>
                            <a class="dropdown-item" asp-area="" asp-controller="Courses" asp-action="Index">View courses</a>
                        </div>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            Teachers
                        </a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                            <a class="dropdown-item" asp-area="" asp-controller="Teachers" asp-action="Create">Register teacher</a>
                            <a class="dropdown-item" asp-area="" asp-controller="Teachers" asp-action="Index">View teachers</a>
                            <a class="dropdown-item" asp-area="" asp-controller="TeachedCourses" asp-action="Create">Assign course</a>
                        </div>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            Students
                        </a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                            <a class="dropdown-item" asp-area="" asp-controller="Students" asp-action="Create">Register student</a>
                            <a class="dropdown-item" asp-area="" asp-controller="Students" asp-action="DeleteSelectedStudent">Delete student</a>
                            <a class="dropdown-item" asp-area="" asp-controller="Students" asp-action="Index">View students</a>
                        </div>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            Secretaries
                        </a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                            <a class="dropdown-item" asp-area="" asp-controller="Secretaries" asp-action="Create">Register secretary</a>
                            <a class="dropdown-item" asp-area="" asp-controller="Secretaries" asp-action="DeleteByCnp">Delete secretary</a>
                            <a class="dropdown-item" asp-area="" asp-controller="Secretaries" asp-action="Index">View secretaries</a>
                        </div>
                    </li>
                    <li class="nav-item">
                        <a class="navbar-brand" href="/">
                            <div class="logo-image">
                                <img id="UserPic" style="border-radius:50%;" alt="image" width="40" height="40" />
                            </div>
                        </a>
                    </li>
                </ul>
            </div>
            <div class="topnav-right">
                <partial name="_LoginPartial" />
            </div>
        </nav>
    </header>

    <div class="container main-container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-dark">
        <div class="container">
            &copy; 2020 - UniversityApp
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    @RenderSection("Scripts", required: false)
    </body>
</html>

UniversityApp/UniversityApp/Views/Shared/_StudentsLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - UniversityApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/student.css" type="text/css" />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.4/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.0.1/js/bootstrap.min.js"></script>
    <link href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.0.1/css/bootstrap.min.css" rel="stylesheet" />
</head>
<body onload="GetUserPicture()">
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark border-bottom box-shadow mb-3">
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                <ul class="navbar-nav flex-grow-1">
                    <li><a asp-area="" asp-controller="Students" asp-action="Home">Home</a></li>
                    <li><a asp-area="" asp-controller="Students" asp-action="Grades">Grades</a></li>
                    <li class="nav-item">
                        <a class="navbar-brand" href="/">
                            <div class="logo-image">
                                <img id="UserPic" style="border-radius:50%;" alt="image" width="40" height="40" />
                            </div>
                        </a>
                    </li>
                </ul>
                <div class="topnav-right">
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>

    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-dark">
        <div class="container">
            &copy; 2020 - UniversityApp
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

UniversityApp/UniversityApp/Views/Shared/_TeachersLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - UniversityApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/student.css" type="text/css" />
    <link href="~/css/site.css" rel="stylesheet" />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.4/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.0.1/js/bootstrap.min.js"></script>
    <link href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.0.1/css/bootstrap.min.css" rel="stylesheet" />
</head>
<body onload="GetUserPicture()">
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark border-bottom box-shadow mb-3">
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                <ul class="navbar-nav flex-grow-1">
                    <li><a asp-area="" asp-controller="Teachers" asp-action="Home">Home</a></li>
                    <li><a asp-area="" asp-controller="Teachers" asp-action="TeachedCourses">Courses&Students</a></li>
                    <li><a asp-area="" asp-controller="Grades" asp-action="Create">Grade Student</a></li>
                   
                    <li class="nav-item">
                        <a class="navbar-brand" href="/">
                            <div class="logo-image">
                                <img id="UserPic" style="border-radius:50%;" alt="image" width="40" height="40" />
                            </div>
                        </a>
                    </li>
                </ul>
                <div class="topnav-right">
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>

    <div class="container main-container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-dark">
        <div class="container">
            &copy; 2020 - UniversityApp
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>